name: Test Tweet

on:
  workflow_dispatch:  # ← 手動で実行できる設定

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install requests requests_oauthlib
      - run: python tweet_test.py  # ← 投稿テスト用プログラムを実行！
